# Generated by Django 6.0.4 on 2026-05-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gram Ağırlığı')),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İşçilik Bedeli')),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Perakende Fiyat')),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toptan Fiyat')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ürün Görseli')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok Adedi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
        ),
    ]
