# Generated by Django 6.0.4 on 2026-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap',
            field=models.BooleanField(default=False),
        ),
    ]
